version: '3'

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:22.0.1
    restart: always
    env_file: keycloak.env
    command:
      - start-dev
    ports:
      - "18080:8080"

